# Generated by Django 4.0.6 on 2022-07-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_put_into_good_hand', '0003_remove_user_name_remove_user_surname_userinf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInf',
        ),
    ]
